### ISSUE TITLE
initial_parts missed 'y','w'

### ISSUE THREAD

**Issue by FredWe** [wey-gu/chinese-graph#2]
https://github.com/wey-gu/chinese-graph/blob/5ab7563e126feb5372d8c1f912359948f39b6964/graph_data_generator.py#L90

这两行可以加上strict=False参数，以修复y，w声母缺失的问题

[Pypinyin：为什么没有 y, w, yu 几个声母？](https://pypi.org/project/pypinyin/#y-w-yu)

**Comment by wey-gu** [comment]
感谢！原来 Handle 把这些不是声母的声母看做了声母，不知道您是否介意直接给 PR 呢？您已经找到关键所在了 :)

**Comment by wey-gu** [comment]
thanks again @FredWe !
